---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-common
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    command: "/lib/systemd/systemd"
    groups:
      - common
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
verifier:
  name: ansible
