# roles/role_name/molecule/default/prepare.yml

# ==========================================
# MOLECULE PREPARE PLAYBOOK
# ==========================================
# Optional pre-tasks run before converge to set up the environment
# (e.g., install required packages, create test users)

- name: Prepare test instance
  hosts: all
  become: true
  tasks:
    - name: Ensure required base packages are installed
      ansible.builtin.package:
        name:
          - sudo
          - python3
          - python3-pip
        state: present
